set fileencodings=utf-8,ucs-bom,gb18030,gbk,gb2312,cp936
set termencoding=utf-8
set encoding=utf-8
set nu
set number
set cursorline
set mouse=a
set selection=exclusive
set selectmode=mouse,key
set autoindent
set tabstop=4
